    sample_risks = [
        # TR-2025-001: Enterprise Data Loss Event
        {
            "risk_id": "TR-2025-001",
            "risk_title": "Enterprise Data Loss Event",
            "risk_category": "Data Management",
            "risk_description": "Local (aka native) backups with or without defined RPO/RTO targets can fail due to critical risk events such as misconfiguration (UniSuper-style account deletion), backup system failures (OVH fire), and ransomware attacks (Kaseya-style encryption). No enterprise-wide 3-2-1 backup strategy exists with applications relying solely on cloud-provider native backup solutions. In most cases, undefined RTO/RPO targets and untested recovery procedures create potential for permanent data loss and business closure.",
            "risk_status": "Active",
            "risk_owner": "Tom Yandell",
            "risk_owner_department": "Information Technology",
            "technology_domain": "Data/Databases",
            "risk_response_strategy": "Mitigate",
            "systems_affected": "All systems with permanent data storage or configuration repositories",
            "ibs_affected": "ALL",
            "business_disruption_impact_rating": "Catastrophic",
            "business_disruption_impact_description": "IBS will be severely disrupted without a recoverable backup and process to restore. The outages could be weeks/months and reputational damage impaired and likely in some cases, completely fail. A full simulated series of non-functional tests in a fully loaded near identical non-production environment is required for each of the IBS applications to determine the full outcome native backup failure event.",
            "business_disruption_likelihood_rating": "Possible",
            "business_disruption_likelihood_description": "Control gaps across all pillars but specifically with the most critical safeguards such as preventative backup testing and integrity monitoring, the detective SOC and TOC and finally the corrective 3-2-1 backups. The Sentinel project maturation of BCP is essential and this scenario must be considered critical in their planning.",
            "preventative_controls_coverage": "Incomplete Coverage",
            "preventative_controls_effectiveness": "Partially Effective",
            "preventative_controls_description": "Configuration Drift Detection - CSPM tool, Wiz, in place, Azure Config in place. Overall infra state drift tool missing. Backup Testing and Integrity Monitoring - no regular testing in place, and no integrity tool(s) are being used. Endpoint Detection and Response - DarkTrace and Microsoft Defender are being reviewed although not clear whether server EP are covered.",
            "detective_controls_coverage": "Incomplete Coverage",
            "detective_controls_effectiveness": "Not Possible to Assess",
            "detective_controls_description": "Security and Technology Operation Centres - SOC service integration with Ontinue progressing for October 2025; build-it-run-it TOC model under development.",
            "corrective_controls_coverage": "Incomplete Coverage",
            "corrective_controls_effectiveness": "Not Possible to Assess",
            "corrective_controls_description": "Business Continuity Site Activation - BCP plan in development through project Sentinel. 3-2-1 Backup Strategy - No strategy in place, dependent on native backup. Crisis Communication and Stakeholder Management - BCP plan in development through project Sentinel. Emergency Vendor and Service Provider Activation - BCP plan in development through project Sentinel.",
            "financial_impact_low": Decimal("19000000.00"),
            "financial_impact_high": Decimal("250000000.00"),
            "financial_impact_notes": "Low: 1 week outage / 100% of GWP. High: 3 months outage / 100% of GWP",
            "planned_mitigations": "TBC",
            "date_identified": date(2025, 8, 28),
            "last_reviewed": date(2025, 9, 8),
            "next_review_date": date(2025, 10, 8),
        },
        # TR-2025-002: GKE Platform Multi-Tenant Failure
        {
            "risk_id": "TR-2025-002",
            "risk_title": "GKE Platform Multi-Tenant Failure",
            "risk_category": "Infrastructure",
            "risk_description": "Multi-tenant GKE platform hosting all front-office systems suffers from infrastructure challenges including resource management guardrails such as memory exhaustion incidents from misconfigured applications, single load balancer dependency for customer whitelisting, and inability to test non-functional failure scenarios due to lack of environment(s). Platform failure would simultaneously affect all containerised workloads preventing quote generation, data analytics, and customer services.",
            "risk_status": "Active",
            "risk_owner": "Tom Yandell",
            "risk_owner_department": "Information Technology",
            "technology_domain": "Infrastructure",
            "risk_response_strategy": "Mitigate",
            "systems_affected": "Algo, DSS, KiWeb, all GKE-hosted front-office applications",
            "ibs_affected": "ALL front-office IBS",
            "business_disruption_impact_rating": "Moderate",
            "business_disruption_impact_description": "IBS will be impaired and could in some cases completely fail. All front-office applications (Algo, DSS, KiWeb) simultaneously affected during platform failures. Quote generation and customer service response times severely impacted. A full simulated series of non-functional tests in a fully loaded near identical non-production environment is required for each of the IBS applications to determine the full outcome of a GKE disruption event.",
            "business_disruption_likelihood_rating": "Possible",
            "business_disruption_likelihood_description": "Control gaps in preventative measures and incomplete implementation of corrective and detective controls. While cluster capacity is adequate, workload-level configurations for resource management and zone distribution are not enforced, and testing capabilities remain limited.",
            "preventative_controls_coverage": "No Controls",
            "preventative_controls_effectiveness": "Not Possible to Assess",
            "preventative_controls_description": "Chaos Engineering - No capability implemented; single production environment prevents failure testing. Disconnected Testing - Not possible as capability not implemented in any environment. Resource management - Improvements underway but preventative testing remains difficult without adequate test environment.",
            "detective_controls_coverage": "Incomplete Coverage",
            "detective_controls_effectiveness": "Partially Effective",
            "detective_controls_description": "Observability - Grafana and Prometheus federated to Google Managed Prometheus providing external visibility. However, missing alerts for cross-platform dependencies and some monitoring gaps remain. Google Cloud Monitoring provides cluster health monitoring but would struggle with significant lights-out service incidents.",
            "corrective_controls_coverage": "Incomplete Coverage",
            "corrective_controls_effectiveness": "Partially Effective",
            "corrective_controls_description": "Multi-Zone Rescheduling - Multi-zone GKE implemented with adequate resource capacity for zone failures. However, workloads lack anti-affinity configurations. Reduced Blast Radius - Spitting out critical application, not implemented. Adequate Resources - Partially implemented with doubled capacity but workload resource requests/limits not properly configured. 3rd Line Support - Run-books and rehearsals possible and partially implemented.",
            "financial_impact_low": Decimal("1500000.00"),
            "financial_impact_high": Decimal("4000000.00"),
            "financial_impact_notes": "Low: 3 hours outage / 100% of GWP. High: 1 day outage / 100% of GWP",
            "planned_mitigations": "Migration to 10.x network, dedicated node pools for critical workloads, comprehensive testing environment, chaos engineering implementation",
            "date_identified": date(2025, 8, 28),
            "last_reviewed": date(2025, 9, 8),
            "next_review_date": date(2025, 10, 8),
        },
    ]