version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./risk_register.db:/app/risk_register.db
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./risk_register.db
      - ALLOWED_ORIGINS=["http://localhost:3000", "http://127.0.0.1:3000", "http://frontend:3000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    networks:
      - risk-register-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api/v1
    depends_on:
      - backend
    networks:
      - risk-register-network

networks:
  risk-register-network:
    driver: bridge

volumes:
  sqlite_data:
