"""Rename RiskUpdate to RiskLogEntry with enhanced audit fields

Revision ID: 70cfbd2a804e
Revises: 0f4ca05ae220
Create Date: 2025-09-11 18:06:35.551786

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70cfbd2a804e"
down_revision: str | Sequence[str] | None = "0f4ca05ae220"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_log_entries",
        sa.Column("log_entry_id", sa.String(length=15), nullable=False),
        sa.Column("risk_id", sa.String(length=12), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("entry_type", sa.String(length=50), nullable=False),
        sa.Column("entry_summary", sa.String(length=500), nullable=False),
        sa.Column("previous_risk_rating", sa.Integer(), nullable=True),
        sa.Column("new_risk_rating", sa.Integer(), nullable=True),
        sa.Column("previous_probability", sa.Integer(), nullable=True),
        sa.Column("new_probability", sa.Integer(), nullable=True),
        sa.Column("previous_impact", sa.Integer(), nullable=True),
        sa.Column("new_impact", sa.Integer(), nullable=True),
        sa.Column("mitigation_actions_taken", sa.String(length=300), nullable=True),
        sa.Column("risk_owner_at_time", sa.String(length=50), nullable=True),
        sa.Column("supporting_evidence", sa.String(length=200), nullable=True),
        sa.Column("entry_status", sa.String(length=20), nullable=True),
        sa.Column("created_by", sa.String(length=50), nullable=False),
        sa.Column("reviewed_by", sa.String(length=50), nullable=True),
        sa.Column("approved_date", sa.Date(), nullable=True),
        sa.Column("business_justification", sa.String(length=300), nullable=True),
        sa.Column("next_review_required", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["risk_id"],
            ["risks.risk_id"],
        ),
        sa.PrimaryKeyConstraint("log_entry_id"),
    )
    op.create_index(
        op.f("ix_risk_log_entries_log_entry_id"),
        "risk_log_entries",
        ["log_entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_risk_log_entries_risk_id"),
        "risk_log_entries",
        ["risk_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_risk_updates_risk_id"), table_name="risk_updates")
    op.drop_index(op.f("ix_risk_updates_update_id"), table_name="risk_updates")
    op.drop_table("risk_updates")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_updates",
        sa.Column("update_id", sa.VARCHAR(length=15), nullable=False),
        sa.Column("risk_id", sa.VARCHAR(length=12), nullable=False),
        sa.Column("update_date", sa.DATE(), nullable=False),
        sa.Column("updated_by", sa.VARCHAR(length=50), nullable=False),
        sa.Column("update_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("update_summary", sa.VARCHAR(length=300), nullable=False),
        sa.Column("previous_risk_rating", sa.VARCHAR(length=20), nullable=True),
        sa.Column("new_risk_rating", sa.VARCHAR(length=20), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["risk_id"],
            ["risks.risk_id"],
        ),
        sa.PrimaryKeyConstraint("update_id"),
    )
    op.create_index(op.f("ix_risk_updates_update_id"), "risk_updates", ["update_id"], unique=False)
    op.create_index(op.f("ix_risk_updates_risk_id"), "risk_updates", ["risk_id"], unique=False)
    op.drop_index(op.f("ix_risk_log_entries_risk_id"), table_name="risk_log_entries")
    op.drop_index(op.f("ix_risk_log_entries_log_entry_id"), table_name="risk_log_entries")
    op.drop_table("risk_log_entries")
    # ### end Alembic commands ###
